import Link from 'next/link';
import './globals.css';
import LoginButton from './LoginButton';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import LogoutButton from './LoginoutButton';
import DarkMode from './DarkMode';
import { cookies } from 'next/headers';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    let session = await getServerSession(authOptions);
    // console.log(session);

    let res = cookies().get('mode');
    // console.log(res.value);
    return (
        <html>
            <body className={res != undefined && res.value === 'dark' ? 'dark-mode' : ''}>
                <div className="navbar">
                    <Link href="/" className="logo">
                        Appleforum
                    </Link>
                    <Link href="/list">List</Link>
                    <Link href="/write">Write</Link>
                    {session ? (
                        <>
                            <span>{session.user.name} </span>
                            <LogoutButton></LogoutButton>
                        </>
                    ) : (
                        <LoginButton></LoginButton>
                    )}
                    <DarkMode></DarkMode>
                </div>
                {children}
            </body>
        </html>
    );
}
